# Generated by Django 4.2.6 on 2023-11-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=25)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=25, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personas_encargadas', models.ManyToManyField(blank=True, related_name='bodega_encargados', to='user.usuario')),
            ],
            options={
                'db_table': 'bodega',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('stock_min', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=25)),
                ('usa_serie', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.modelo')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('garantia', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('nombre_bodega', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_bodega', to='store.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_producto', to='store.producto')),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unidad'),
        ),
        # migrations.CreateModel(
        #     name='Movimiento',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('cantidad', models.PositiveIntegerField()),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('bodega_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_recepcion', to='store.bodega')),
        #         ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
        #     ],
        #     options={
        #         'db_table': 'movimiento',
        #     },
        # ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
                ('tipomovimiento', models.CharField(max_length=10, choices=[
                    ('INGRESO', 'INGRESO'),
                    ('EGRESO', 'EGRESO'),
                ])),
                ('descripcion', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movimiento',
            },
        ),
    ]
