# Generated by Django 4.2.6 on 2023-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_producto_marca_alter_producto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
