# Generated by Django 4.2.6 on 2023-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_movimiento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
