# Generated by Django 4.2.6 on 2023-11-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rol_permisos'),
        ('store', '0005_alter_stock_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usuario'),
            preserve_default=False,
        ),
    ]
