# Generated by Django 4.2.6 on 2023-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_movimiento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='estado',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='series',
            field=models.ManyToManyField(blank=True, to='store.serie'),
        ),
    ]
