# Generated by Django 4.2.6 on 2023-12-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_serie_estado_movimiento_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
