# Generated by Django 4.2.6 on 2023-12-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_serie_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='series',
        ),
        migrations.AlterField(
            model_name='serie',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie_bodega', to='store.bodega'),
        ),
    ]
