# Generated by Django 4.2.6 on 2023-12-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_movimiento_series_alter_serie_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='series',
            field=models.ManyToManyField(blank=True, to='store.serie'),
        ),
    ]
