# Generated by Django 4.2.6 on 2023-12-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_movimiento_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='estado',
        ),
        migrations.AlterField(
            model_name='serie',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
