# Generated by Django 4.2.6 on 2023-12-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_serie_estado_alter_serie_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoMovimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'motivo_movimiento',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='motivo_movimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.motivomovimiento'),
            preserve_default=False,
        ),
    ]
