# Generated by Django 4.2.6 on 2023-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_motivomovimiento_movimiento_motivo_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='motivo_movimiento',
        ),
        migrations.DeleteModel(
            name='MotivoMovimiento',
        ),
    ]
