# Generated by Django 4.2.6 on 2023-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_movimiento_motivo_movimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoMovimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'motivo_movimiento',
            },
        ),
    ]
