# Generated by Django 4.2.6 on 2023-12-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_motivomovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='motivo_movimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.motivomovimiento'),
            preserve_default=False,
        ),
    ]
