# Generated by Django 4.2.6 on 2024-01-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_movimiento_motivo_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='motivo',
        ),
    ]
