# Generated by Django 4.2.6 on 2024-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_movimiento_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
