# Generated by Django 4.2.6 on 2024-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_bodega_created_at_alter_bodega_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='id_actividad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
