# Generated by Django 4.2.6 on 2024-03-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usuariowishupapi'),
        ('store', '0019_movimiento_id_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bodega'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='motivo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.motivomovimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.producto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.unidad'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serie_bodega', to='store.bodega'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serie_producto', to='store.producto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bodega'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.producto'),
        ),
    ]
