# Generated by Django 4.2.6 on 2024-03-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_movimiento_bodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.bodega'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.producto'),
        ),
    ]
