# Generated by Django 4.2.6 on 2024-03-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_stock_bodega_alter_stock_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bodega'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.producto'),
        ),
    ]
