# Generated by Django 4.2.6 on 2024-03-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_movimiento_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo2',
            field=models.CharField(blank=True, default='SIMPLE', max_length=35),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_real',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='estado',
            field=models.CharField(blank=True, default='ACTIVO', max_length=35),
        ),
        migrations.AddField(
            model_name='serie',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serie_proveedor', to='store.proveedor'),
        ),
        migrations.AddField(
            model_name='serie',
            name='tipo',
            field=models.CharField(blank=True, default='SIMPLE', max_length=35),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='serie',
            name='serie',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
