# Generated by Django 4.2.6 on 2024-03-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_movimiento_proveedor_producto_tipo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='nombre_bodega',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='nombre_producto',
        ),
    ]
