# Generated by Django 4.2.6 on 2024-03-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_stock_nombre_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_simple',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
