# Generated by Django 4.2.6 on 2024-03-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_producto_nombre_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='serie',
            name='stock',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
