# Generated by Django 4.2.6 on 2024-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_serie_ubicacion_serie_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='garantia',
            field=models.CharField(blank=True, default='NO', max_length=2),
        ),
    ]
