# Generated by Django 4.2.6 on 2024-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_serie_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='garantia',
            field=models.CharField(blank=True, default='NO', max_length=5),
        ),
    ]
