# Generated by Django 4.2.6 on 2024-03-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_serie_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
