# Generated by Django 4.2.6 on 2023-12-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rol_permisos'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='usuario_agendo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_user_agenda', to='user.usuario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_user_revision', to='user.usuario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_user_solicitud', to='user.usuario'),
        ),
    ]
