# Generated by Django 4.2.6 on 2023-12-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_solicitud_usuario_agendo_solicitud_usuario_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(blank=True, max_length=220, null=True),
        )
    ]
