# Generated by Django 4.2.6 on 2023-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_solicitud_estado_solicitud_fecha_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_agenda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
