# Generated by Django 4.2.6 on 2023-12-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_solicitud_fecha_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_agenda',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
