# Generated by Django 4.2.6 on 2023-12-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_solicitud_fecha_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='idcliente',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
