# Generated by Django 4.2.6 on 2024-01-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_solicitud_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='idcliente',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
