# Generated by Django 4.2.6 on 2024-01-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_solicitud_idcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='celular',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion_anterior',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='foto_casa',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='horarios_disponibles',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='latitud',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='latitud_anterior',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='latitud_nueva',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud_anterior',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud_nueva',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombres_cliente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observacion_diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='plan_contratar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='plan_vigente',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='senal_potencia',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tecnologia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
