# Generated by Django 4.2.6 on 2024-01-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_solicitud_cedula_solicitud_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='tiposolicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(default='prueba', max_length=60),
            preserve_default=False,
        ),
    ]
