# Generated by Django 4.2.6 on 2024-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_remove_solicitud_tiposolicitud_solicitud_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='plan_vigente',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='gestion_operador',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observacion',
            field=models.TextField(blank=True),
        ),
    ]
