# Generated by Django 4.2.6 on 2024-01-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_remove_solicitud_plan_vigente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='casa_npisos',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cliente_tiene_equipo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(blank=True, max_length=220),
        ),
    ]
