# Generated by Django 4.2.6 on 2024-01-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_solicitud_casa_npisos_solicitud_cliente_tiene_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(blank=True, max_length=220, null=True),
        ),
    ]
