# Generated by Django 4.2.6 on 2024-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_kit_created_at_alter_kit_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='foto_casa',
            field=models.TextField(blank=True),
        ),
    ]
