# Generated by Django 4.2.6 on 2024-02-29 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usuario_uid'),
        ('agenda', '0014_alter_solicitud_foto_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojadeTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=35)),
                ('tipo', models.CharField(max_length=60)),
                ('datos', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hojatrabajo_user_solicitud', to='user.usuario')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hojatrabajo_user_revision', to='user.usuario')),
            ],
            options={
                'db_table': 'hojatrabajo',
            },
        ),
    ]
