# Generated by Django 4.2.6 on 2024-02-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_hojadetrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojadetrabajo',
            name='tipo',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
