# Generated by Django 4.2.6 on 2024-03-03 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_hojadetrabajo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wisphub',
            fields=[
                ('idservicio', models.CharField(blank=True,max_length=15)),
                ('idzona', models.CharField(blank=True, max_length=25)),
                ('zona', models.CharField(blank=True, max_length=75)),
                ('idplan', models.CharField(blank=True, max_length=25)),
                ('plan', models.CharField(blank=True, max_length=75)),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('usuariorb', models.CharField(blank=True, max_length=55)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hojatrabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wisphubhojatrabajo', to='agenda.hojadetrabajo')),
            ],
            options={
                'db_table': 'wisphub',
            },
        ),
    ]
