# Generated by Django 4.2.6 on 2024-03-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_wisphub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojadetrabajo',
            name='id_actividad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
