# Generated by Django 4.2.6 on 2024-03-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usuariowishupapi'),
        ('store', '0019_movimiento_id_actividad'),
        ('agenda', '0018_hojadetrabajo_id_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojadetrabajo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hojatrabajo_user_solicitud', to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='hojadetrabajo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hojatrabajo_user_revision', to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='kitxproducto',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.kit'),
        ),
        migrations.AlterField(
            model_name='kitxproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.producto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario_agendo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_user_agenda', to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_user_revision', to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_user_solicitud', to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='wisphub',
            name='hojatrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wisphubhojatrabajo', to='agenda.hojadetrabajo'),
        ),
    ]
