# Generated by Django 4.2.6 on 2024-03-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_alter_hojadetrabajo_usuario_creacion_and_more'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='wisphub',
            name='idservicio',
            field=models.CharField(max_length=15),
        ),
    ]
