# Generated by Django 4.2.6 on 2024-03-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_remove_wisphub_iduser_alter_wisphub_idservicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wisphub',
        ),
    ]
