# Generated by Django 4.2.6 on 2024-03-10 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usuariowishupapi'),
        ('agenda', '0022_delete_wisphub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wisphub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idzona', models.CharField(blank=True, max_length=25)),
                ('zona', models.CharField(blank=True, max_length=75)),
                ('idplan', models.CharField(blank=True, max_length=25)),
                ('plan', models.CharField(blank=True, max_length=75)),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('usuariorb', models.CharField(blank=True, max_length=55)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hojatrabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wisphubhojatrabajo', to='agenda.hojadetrabajo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wisphub_ususario_crea', to='user.usuario')),
            ],
            options={
                'db_table': 'wisphub',
            },
        ),
    ]
