# Generated by Django 4.2.6 on 2024-03-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0023_wisphub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wisphub',
            old_name='idplan',
            new_name='id_plan',
        ),
    ]
