# Generated by Django 4.2.6 on 2024-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_alter_hojadetrabajo_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='senal_potencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
