# Generated by Django 4.2.6 on 2024-02-09 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0019_movimiento_id_actividad'),
        ('user', '0004_alter_permiso_created_at_alter_permiso_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_plata', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='user.usuario')),
            ],
            options={
                'db_table': 'recepcion',
            },
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_comprobante', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto_gasolina', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustibles', to='store.bodega')),
                ('id_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustibles', to='user.usuario')),
            ],
            options={
                'db_table': 'combustible',
            },
        ),
    ]
