# Generated by Django 4.2.6 on 2024-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='foto_comprobante',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='foto_plata',
            field=models.TextField(blank=True),
        ),
    ]
