# Generated by Django 4.2.6 on 2024-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_combustible_foto_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='monto_gasolina',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='monto',
            field=models.FloatField(),
        ),
    ]
