# Generated by Django 4.2.6 on 2023-12-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta'),
            preserve_default=False,
        ),
    ]
