# Generated by Django 4.2.6 on 2023-12-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_movimiento_series'),
        ('rutas', '0003_alter_actividad_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bodega'),
        ),
    ]
