# Generated by Django 4.2.6 on 2024-01-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_solicitud_idcliente'),
        ('rutas', '0005_actividad_estado_actividad_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.solicitud'),
            preserve_default=False,
        ),
    ]
