# Generated by Django 4.2.6 on 2024-01-12 20:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rol_permisos'),
        ('rutas', '0006_alter_actividad_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='usuario_mod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(max_length=75),
        ),
        migrations.CreateModel(
            name='ActividadHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=200)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.actividad')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
                ('usuario_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario')),
            ],
            options={
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
