# Generated by Django 4.2.6 on 2024-01-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_actividad_usuario_mod_alter_actividad_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actividadhistorial',
            table='actividad_historial',
        ),
    ]
