# Generated by Django 4.2.6 on 2024-01-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_alter_actividadhistorial_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tipo',
        ),
    ]
