# Generated by Django 4.2.6 on 2024-01-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_remove_actividad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
