# Generated by Django 4.2.6 on 2024-01-23 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_alter_actividad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tiempo_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tiempo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tiempo_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tiempo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
