# Generated by Django 4.2.6 on 2024-01-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_permiso_created_at_alter_permiso_updated_at_and_more'),
        ('rutas', '0011_actividad_tiempo_fin_actividad_tiempo_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_tecnico', to='user.usuario'),
        ),
    ]
