# Generated by Django 4.2.6 on 2024-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0012_actividad_id_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='distancia',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
