# Generated by Django 4.2.6 on 2024-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0013_actividad_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='Actividades',
            field=models.ManyToManyField(blank=True, related_name='ruta_actividad', to='rutas.actividad'),
        ),
    ]
