# Generated by Django 4.2.6 on 2024-01-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0014_ruta_actividades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='Actividades',
            new_name='actividades',
        ),
    ]
