# Generated by Django 4.2.6 on 2024-01-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_kit_created_at_alter_kit_updated_at_and_more'),
        ('rutas', '0015_rename_actividades_ruta_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.solicitud'),
        ),
    ]
