# Generated by Django 4.2.6 on 2024-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0016_alter_actividad_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tiempo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tiempo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
