# Generated by Django 4.2.6 on 2024-01-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0017_alter_actividad_tiempo_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='ruta',
        ),
    ]
