# Generated by Django 4.2.6 on 2024-01-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0018_remove_actividad_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadhistorial',
            name='ruta',
        ),
    ]
