# Generated by Django 4.2.6 on 2024-01-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0019_remove_actividadhistorial_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='actividades',
            field=models.ManyToManyField(blank=True, to='rutas.actividad'),
        ),
    ]
