# Generated by Django 4.2.6 on 2024-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0020_alter_ruta_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='actividades',
            field=models.ManyToManyField(blank=True, related_name='ruta_actividad', to='rutas.actividad'),
        ),
    ]
