# Generated by Django 4.2.6 on 2024-02-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0021_alter_ruta_actividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='actividades',
        ),
        migrations.AddField(
            model_name='actividad',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta'),
        ),
    ]
