# Generated by Django 4.2.6 on 2024-02-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0022_remove_ruta_actividades_actividad_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadhistorial',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta'),
        ),
    ]
