# Generated by Django 4.2.6 on 2024-02-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0023_actividadhistorial_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadhistorial',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='rutas.ruta'),
        ),
    ]
