# Generated by Django 4.2.6 on 2024-02-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0024_alter_actividadhistorial_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='nombre',
        ),
    ]
