# Generated by Django 4.2.6 on 2024-02-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_permiso_created_at_alter_permiso_updated_at_and_more'),
        ('rutas', '0025_remove_actividad_nombre_remove_ruta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='user.usuario'),
        ),
    ]
