# Generated by Django 4.2.6 on 2024-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0026_alter_actividad_id_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='estado',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
