# Generated by Django 4.2.6 on 2024-03-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0027_ruta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='km',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
