# Generated by Django 4.2.6 on 2024-03-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_movimiento_id_actividad'),
        ('rutas', '0028_actividad_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='id_cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bodega'),
        ),
    ]
