# Generated by Django 4.2.6 on 2024-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usuariowishupapi'),
        ('store', '0019_movimiento_id_actividad'),
        ('agenda', '0018_hojadetrabajo_id_actividad'),
        ('rutas', '0029_actividad_id_cuadrilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.bodega'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.solicitud'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='usuario_mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usuario'),
        ),
    ]
