# Generated by Django 4.2.6 on 2024-03-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usuariowishupapi'),
        ('store', '0019_movimiento_id_actividad'),
        ('rutas', '0030_alter_actividad_id_cuadrilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='id_reagendado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadhistorial',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.actividad'),
        ),
        migrations.AlterField(
            model_name='actividadhistorial',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='actividadhistorial',
            name='usuario_mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.bodega'),
        ),
    ]
