# Generated by Django 4.2.6 on 2024-03-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usuariowishupapi'),
        ('agenda', '0025_alter_hojadetrabajo_usuario_creacion_and_more'),
        ('store', '0022_alter_stock_bodega_alter_stock_producto'),
        ('rutas', '0031_actividad_id_reagendado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bodega'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.solicitud'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='usuario_mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='actividadhistorial',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.actividad'),
        ),
        migrations.AlterField(
            model_name='actividadhistorial',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='actividadhistorial',
            name='usuario_mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usuario'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bodega'),
        ),
    ]
