# Generated by Django 4.2.6 on 2024-04-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0032_alter_actividad_id_cuadrilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='motivo_cancelado',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
