# Generated by Django 4.2.6 on 2024-04-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0033_actividad_motivo_cancelado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='motivo_cancelado',
        ),
    ]
