# Generated by Django 4.2.6 on 2023-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permiso_rol_created_at_usuario_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='user.permiso'),
        ),
    ]
