# Generated by Django 4.2.6 on 2024-02-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_permiso_created_at_alter_permiso_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
