# Generated by Django 4.2.6 on 2024-03-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usuario_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioWishupApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
                ('plan_internet', models.CharField(max_length=10)),
                ('zona', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=123)),
                ('usuario_rb', models.CharField(max_length=123)),
                ('cedula', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'usuarioWishupapi',
            },
        ),
    ]
