# Generated by Django 4.2.6 on 2024-03-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='sistema',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
